-- Phase 102 (seed): production built-in catalog from builtinCatalog.ts (exclude hub-practice-login)

insert into public.service_registry (
  id,
  display_name,
  primary_url,
  login_url,
  category_id,
  icon,
  adapter_id,
  login_fields,
  source_type,
  service_status,
  metadata,
  login_url_status,
  owner_user_id
)
values
  (
    'hapoalim',
    'בנק הפועלים',
    'https://www.bankhapoalim.co.il',
    null,
    'banking',
    '🏦',
    null,
    '[{"id":"username","label":"שם משתמש","type":"text"},{"id":"password","label":"סיסמה","type":"password"}]'::jsonb,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.bankhapoalim.co.il"}'::jsonb,
    'unknown',
    null
  ),
  (
    'leumi',
    'בנק לאומי',
    'https://www.leumi.co.il',
    null,
    'banking',
    '🏦',
    null,
    null,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.leumi.co.il"}'::jsonb,
    'unknown',
    null
  ),
  (
    'discount',
    'דיסקונט',
    'https://www.discountbank.co.il',
    null,
    'banking',
    '🏦',
    null,
    null,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.discountbank.co.il"}'::jsonb,
    'unknown',
    null
  ),
  (
    'mizrahi',
    'מזרחי טפחות',
    'https://www.mizrahi-tefahot.co.il',
    null,
    'banking',
    '🏦',
    null,
    null,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.mizrahi-tefahot.co.il"}'::jsonb,
    'unknown',
    null
  ),
  (
    'clalit',
    'כללית',
    'https://www.clalit.co.il',
    'https://e-services.clalit.co.il/onlineweb/general/login.aspx',
    'health',
    '🏥',
    null,
    '[{"id":"idNumber","label":"מספר תעודת זהות","type":"text"},{"id":"userCode","label":"קוד משתמש","type":"text"},{"id":"password","label":"סיסמה","type":"password"}]'::jsonb,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.clalit.co.il"}'::jsonb,
    'valid',
    null
  ),
  (
    'maccabi',
    'מכבי',
    'https://www.maccabi4u.co.il',
    null,
    'health',
    '🏥',
    null,
    null,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.maccabi4u.co.il"}'::jsonb,
    'unknown',
    null
  ),
  (
    'meuhedet',
    'מאוחדת',
    'https://www.meuhedet.co.il',
    null,
    'health',
    '🏥',
    null,
    null,
    'built_in',
    'active',
    '{}'::jsonb,
    'unknown',
    null
  ),
  (
    'leumit',
    'לאומית',
    'https://www.leumit.co.il',
    null,
    'health',
    '🏥',
    null,
    null,
    'built_in',
    'active',
    '{}'::jsonb,
    'unknown',
    null
  ),
  (
    'shufersal',
    'שופרסל',
    'https://www.shufersal.co.il',
    'https://www.shufersal.co.il/online/he/login',
    'shopping',
    '🛒',
    null,
    '[{"id":"email","label":"כתובת מייל","type":"text"},{"id":"password","label":"סיסמה","type":"password"}]'::jsonb,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.shufersal.co.il"}'::jsonb,
    'valid',
    null
  ),
  (
    'rami-levy',
    'רמי לוי',
    'https://www.rami-levy.co.il',
    null,
    'shopping',
    '🛒',
    null,
    null,
    'built_in',
    'active',
    '{}'::jsonb,
    'unknown',
    null
  ),
  (
    'amazon-il',
    'Amazon ישראל',
    'https://www.amazon.co.il',
    null,
    'shopping',
    '🛒',
    null,
    null,
    'built_in',
    'active',
    '{}'::jsonb,
    'unknown',
    null
  ),
  (
    'ksp',
    'KSP',
    'https://www.ksp.co.il',
    null,
    'shopping',
    '🛒',
    null,
    null,
    'built_in',
    'active',
    '{}'::jsonb,
    'unknown',
    null
  ),
  (
    'htzone',
    'הייטקזון',
    'https://www.htzone.co.il',
    'https://www.htzone.co.il/login',
    'shopping',
    '🛒',
    'htzone',
    '[{"id":"email","label":"אימייל","type":"text"},{"id":"password","label":"סיסמה","type":"password"}]'::jsonb,
    'built_in',
    'active',
    '{"faviconSiteUrl":"https://www.htzone.co.il"}'::jsonb,
    'valid',
    null
  )
on conflict (id) do update set
  display_name = excluded.display_name,
  primary_url = excluded.primary_url,
  login_url = excluded.login_url,
  category_id = excluded.category_id,
  icon = excluded.icon,
  adapter_id = excluded.adapter_id,
  login_fields = excluded.login_fields,
  source_type = excluded.source_type,
  service_status = excluded.service_status,
  metadata = excluded.metadata,
  login_url_status = excluded.login_url_status,
  owner_user_id = excluded.owner_user_id,
  updated_at = now();
